### ISSUE TITLE
关于http代理在高并发下请求错误的情况

### ISSUE THREAD

**Issue by fofohi** [helloh2o/hoz#1]
这样的项目我是用来加速我的一个外网的网页游戏的,该游戏每次刷新页面大概会有大量的http请求,包含css js 图片等静态文件,大并发下会导致一部分css 和js 请求加载失败,socks5协议是ok的,但是http出现问题,作者是否有时间看看.
游戏域名
granbluefantasy.jp
另外申请buff那边希望能改进成使用pool,扔vps上 接受大量并发 现在直接就崩溃

**Comment by helloh2o** [comment]
这个写了有点儿久了， TLS下其他加密有点问题，你使用little加密方式 不会有问题@https://github.com/helloh2o/hoz/commit/16ee4fb0095608f645cb49649d0cedef19922a3e

你也可以把日志，贴出来看看。
